name: CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install, build
        run: |
          curl -o- -L https://yarnpkg.com/install.sh | bash
          cd client
          yarn
          cd ..
          yarn
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.8.x
          npm install -g nodemon
          lhci collect --start-server-command="yarn dev" --numberOfRuns=1 --url=http://localhost:3000 --startServerReadyPattern="You can now view client in the browser" startServerReadyTimeout=1000000
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}